name: Build TrickingLibrary
on: push

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls
